[package]
name = "debugging101"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "write_data"

[[bin]]
name = "lookup_index"

[[bin]]
name = "driver"
